In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [3]:
## Vocabular size 
voc_size = 10000

In [4]:
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[2182, 2597, 8721, 1653],
 [2182, 2597, 8721, 9726],
 [2182, 5079, 8721, 9075],
 [1714, 6151, 7842, 2937, 9546],
 [1714, 6151, 7842, 2937, 7224],
 [4796, 2182, 5923, 8721, 3647],
 [2521, 1995, 6744, 2937]]

In [5]:
## word embedding representation 
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np 



In [7]:
sent_length = 8 
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2182 2597 8721 1653]
 [   0    0    0    0 2182 2597 8721 9726]
 [   0    0    0    0 2182 5079 8721 9075]
 [   0    0    0 1714 6151 7842 2937 9546]
 [   0    0    0 1714 6151 7842 2937 7224]
 [   0    0    0 4796 2182 5923 8721 3647]
 [   0    0    0    0 2521 1995 6744 2937]]


In [8]:
# feature representation 
dim = 10 

In [9]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length = sent_length)) ## Input parameters to the Embedding layer
model.compile('adam','mse')

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [11]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 272ms/step


array([[[-3.2371007e-02,  2.7327564e-02, -1.8381298e-02,  1.1707962e-02,
         -2.1238232e-02, -4.5255907e-03,  3.6704540e-03,  3.9696727e-02,
         -1.0807168e-02, -1.1580065e-04],
        [-3.2371007e-02,  2.7327564e-02, -1.8381298e-02,  1.1707962e-02,
         -2.1238232e-02, -4.5255907e-03,  3.6704540e-03,  3.9696727e-02,
         -1.0807168e-02, -1.1580065e-04],
        [-3.2371007e-02,  2.7327564e-02, -1.8381298e-02,  1.1707962e-02,
         -2.1238232e-02, -4.5255907e-03,  3.6704540e-03,  3.9696727e-02,
         -1.0807168e-02, -1.1580065e-04],
        [-3.2371007e-02,  2.7327564e-02, -1.8381298e-02,  1.1707962e-02,
         -2.1238232e-02, -4.5255907e-03,  3.6704540e-03,  3.9696727e-02,
         -1.0807168e-02, -1.1580065e-04],
        [-3.8828503e-02, -1.6121853e-02, -1.2904681e-02,  4.9557019e-02,
         -2.5242083e-03,  2.2107374e-02,  4.8736084e-02,  4.5487154e-02,
          1.6488656e-03,  3.0551586e-02],
        [-5.8497079e-03, -8.6615086e-03,  2.7046356e-02, -2.